package org.katia.editor.ui.menubar;

public enum MenuAction {
    CREATE_NEW_PROJECT,
    OPEN_PROJECT,
    SAVE_PROJECT,
    EXIT,


    TOGGLE_HIERARCHY_WINDOW,
    TOGGLE_INSPECTOR_WINDOW,
    TOGGLE_PROJECT_WINDOW,
    TOGGLE_CONSOLE_WINDOW,

    CREATE_NEW_SCENE,
    OPEN_SCENE,
    SAVE_SCENE,

    PROJECT_SETTINGS,

    RUN_GAME,

    ABOUT,
}
